version: '3'
services:

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27020:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: