server:
  port: 8081

spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://localhost:5440/auth
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27020/authentication
      auto-index-creation: true
    redis:
      database: 0
      host: localhost
      port: 6380

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/oauth2/default

jwt:
  secret: myJwtSecret
  expiration: 86400000  # 1 day in milliseconds

